# 기본 활성화 룰 중 제외할 것들
disabled_rules:
  - trailing_whitespace
  - multiple_closures_with_trailing_closure
  
# 선택적으로 적용할 룰
opt_in_rules:
  - empty_count # .isEmpty 대신 .count == 0를 사용하면 경고
included: # 린트 과정에 포함할 파일 경로. 이 항목이 존재하면 `--path`는 무시됨
excluded: # 린트 과정에서 무시할 파일 경로. `included`보다 우선순위 높음
- Molio/Source/App/AppDelegate.swift
- Molio/Source/App/SceneDelegate.swift
# DTO 모델 생성 시 추가하기
# 테스트 타겟 생성 시 추가하기

# 설정 가능한 룰은 이 설정 파일에서 커스터마이징 가능
# 경고나 에러 중 하나를 발생시키는 룰은 위반 수준을 설정 가능
force_cast: warning # 암시적으로 지정
force_try:
  severity: warning # 명시적으로 지정
  
# 경고 및 에러 둘 다 존재하는 룰의 경우 값을 하나만 지정하면 암시적으로 경고 수준에 설정됨
line_length:
  warning: 120
  ignores_comments: true
  
# 함수 길이 100줄로 제한
function_body_length:
  warning: 100
  
large_tuple:
    warning: 3
nesting:
  type_level:
    warning: 3  # 3단계까지 중첩 허용, 그 이상이면 경고
    error: 5    # 5단계 이상이면 에러 발생
type_name:
  min_length: 2 # 최소 길이 설정
  max_length: 40  # 최대 길이 설정

identifier_name:
  min_length: # 식별자 길이가 3 이상이어야 함
    error: 2
  excluded: # 규칙에서 제외할 식별자
    - id
    - ok